#!/usr/bin/env bash

if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS=("alacritty" "btop" "git" "nvim" "ranger" "scripts" "tealdeer" "tmux" "zsh")
fi

if [[ -e $HOME/.zshrc ]]; then
	rm "$HOME/.zshrc"
fi

for folder in "${STOW_FOLDERS[@]}"; do
	if stow -n "$folder" | grep -q 'Would perform stow of'; then
		continue
	else
		stow -D "$folder"
	fi

	stow "$folder"
done
