#!/usr/bin/env bash

if [[ -z $STOW_FOLDERS ]]; then
	# btop below
	STOW_FOLDERS=("alacritty" "git" "nvim" "ranger" "tealdeer" "tmux" "zsh")
fi

if [[ -e $HOME/.zshrc ]]; then
	rm "$HOME/.zshrc"
fi

for folder in "${STOW_FOLDERS[@]}"; do
	if stow -n "$folder" | grep -q 'Would perform stow of'; then
		continue
	else
		stow -D "$folder"
	fi

	stow "$folder"
done

# Btop contains symlinks therefore needs to be treated separately
stow --target="$HOME"/snap/btop/current btop
