return {
  -- add any tools you want to have installed below
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "actionlint",
        "ansible-language-server",
        "ansible-lint",
        "shellcheck",
        "shfmt",
        "stylua",
        -- "autoflake",
        -- "autopep8",
        "basedpyright",
        "bash-debug-adapter",
        "bash-language-server",
        "black",
        "blackd-client",
        "buildifier",
        "bzl",
        "clang-format",
        "clangd",
        "cmake-language-server",
        "cmakelang",
        "cmakelint",
        "commitlint",
        "cpplint",
        "cpptools",
        "debugpy",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "fixjson",
        -- "flake8",
        -- "flakeheaven",
        "gitlint",
        "grammarly-languageserver",
        "isort",
        "jedi-language-server",
        "jinja-lsp",
        "jq",
        "jq-lsp",
        "json-lsp",
        "json-to-struct",
        "jsonld-lsp",
        "jsonlint",
        "ltex-ls",
        "luacheck",
        "luaformatter",
        "markdown-oxide",
        "markdown-toc",
        "markdownlint",
        "markdownlint-cli2",
        "markmap-cli",
        "marksman",
        "markuplint",
        "mypy",
        "prettier",
        "prettierd",
        -- "pydocstyle",
        -- "pyflakes",
        -- "pyink",
        -- "pylama",
        "pylint",
        -- "pylyzer",
        -- "pyment",
        "pyproject-flake8",
        -- "pyre",
        "pyright",
        "python-lsp-server",
        "ruff",
        "ruff-lsp",
        "rust-analyzer",
        "shellharden",
        "sql-formatter",
        "sqlfluff",
        "sqlfmt",
        "sqlls",
        "sqls",
        "systemdlint",
        "write-good",
        "xmlformatter",
        "yaml-language-server",
        "yamlfix",
        "yamlfmt",
        "yamllint",
        "yapf",
      },
    },
  },
}
